version: '2.0'
services: 
  registry: 
    restart: always 
    image: registry:2.7 
    container_name: registry11
    ports: 
      - 5001:5000 
    volumes: 
      - /mnt/d/registry-data:/var/lib/registry 
      - ./registry-config/simple.yaml:/etc/docker/registry/config.yml 
  ui: 
    image: joxit/docker-registry-ui:latest 
    container_name: ui11
    ports: 
      - 8080:80 
    environment: 
      - REGISTRY_TITLE=Local Docker Registry 
      - REGISTRY_URL=http://localhost:5001  
      - SINGLE REGISTRY=true 
    depends_on: 
      - registry 
